name: Bundle and Deploy

description: Run a deployment
inputs:
  where-to:
    description: Where this deployment will be sent
    required: true
runs:
  using: composite
  steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDDTHHmmss
        utcOffset: "+00:00"
    - name: Bundle Files
      shell: bash
      env:
        TIMESTAMP: "${{ steps.current-time.outputs.formattedTime }}"
      run: tar -zcf ${TIMESTAMP}.tgz -C ./dist .
    - name: Transfer Bundle to ${{ inputs.where-to }} Server
      env:
        TIMESTAMP: "${{ steps.current-time.outputs.formattedTime }}"
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        source: "${{ steps.current-time.outputs.formattedTime }}.tgz"
        target: "${{ secrets.DEPLOYMENT_PATH }}/deploys"
    - name: Run release script on ${{ inputs.where-to }}
      env:
        TIMESTAMP: "${{ steps.current-time.outputs.formattedTime }}"
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        script: "${{ secrets.DEPLOYMENT_PATH }}/release.sh ${{ steps.current-time.outputs.formattedTime }}"
