name: Bundle and Deploy

description: Run a deployment
inputs:
  where-to:
    description: Where this deployment will be sent
    required: true
  host:
    description: The host this deployment will be sent to
    required: true
  username:
    description: The username on the host
    required: true
  key:
    description: The private key used connect to the host
    required: true
  path:
    description: The base path on the host the deployment will go
    required: true
  bundle-directory:
    description: The root directory to be bundled for deployment
    required: false
    default: .
runs:
  using: composite
  steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDDTHHmmss
        utcOffset: "+00:00"
    - name: Bundle Files
      shell: bash
      env:
        TIMESTAMP: "${{ steps.current-time.outputs.formattedTime }}"
      run: tar -zcf ${TIMESTAMP}.tgz -C ${{ inputs.bundle-directory }} --exclude-from exclude-on-deploy-files.txt .
    - name: Transfer Bundle to ${{ inputs.where-to }} Server
      env:
        TIMESTAMP: "${{ steps.current-time.outputs.formattedTime }}"
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        source: "${{ steps.current-time.outputs.formattedTime }}.tgz"
        target: "${{ inputs.path }}/deploys"
    - name: Run release script on ${{ inputs.where-to }}
      env:
        TIMESTAMP: "${{ steps.current-time.outputs.formattedTime }}"
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        script: "${{ inputs.path }}/release.sh ${{ steps.current-time.outputs.formattedTime }}"
